---
id: Autoloader
name: Autoloader
full: Autoloader library
description: Autoload implementation and class loading manager for Horde.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Autoloader
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 2.1.3
  api: 2.1.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
